### ISSUE TITLE
storing of crossword-data in php

### ISSUE THREAD

**Issue by LeanDerVorausdenkende** [LeanDerVorausdenkende/10a-Kreuzwortraetselwettbewerb#2]
First, we need to distinguish between real cossword puzzles and word searchs. I don't know anything about php data types, but we'll need some kind of dict to store the "type" and the puzzle itself.
For this, we could use a two-dimensional array (if this is supportet in php). So we'll have kind of a grid and can store the content of every cell in the proper position of the 2d-array. 

How this data will be read is specified by the type of the puzzle: 

The crossword puzzle will have another dict in every cell, including another "type" attr (description of a word, cell for a letter, blank cell for gaps between the words) and the content (description/letter/null). Maybe we even have to prepare for two description texts in a single cell.
![crossword_puzzle](https://user-images.githubusercontent.com/57540049/78876381-8d4f2200-7a4f-11ea-99bc-1f956533b812.png)

For the word search, there's only a one-letter-string that will be showed in this position, that's not much work, we could do this without an additional "type"-value or just make every word serch cell type = letter. But in addition to that, we need to store the included words somewhere. The user will mark some letters in a row and we have to check whether it is one of the words he/she is searching for or not. We could use an additional array that stores all the available words. I think, storing them by simply memorizing the positions of the first and last letter would be a simple and good option, these two values will make a clear definition of the word possible since there won't be more than one word with the same start and end. When the user now marks a group of letters, we'll take these two positions and compare it to the answer-array.

What's your opinion about this?

**Comment by AntonderDenker** [comment]
Wow. Ok, first, I absolutly go with your concept of the two variants, you discribed in the text above. I like the idea with different cell-types and yeah, it's no problem to storage data in two-dimensional arrays by using PHP. I don't have to add something to the second part, I agree with all of  them. Now, since you showed me your plan, I'm realy excited to work on it.

**Comment by LeanDerVorausdenkende** [comment]
So I will take care of the crossword-template input. Should I just store it in JS variables and you can transfer them to PHP or is the better version storing it directly in PHP (in this case i'll just comment the required actions in the JS-code)?

**Comment by AntonderDenker** [comment]
You need to store the data in JS. Only then I can send them to PHP by a form.

**Comment by LeanDerVorausdenkende** [comment]
I think, this is all solved now.
