### ISSUE TITLE
strange error in /create

### ISSUE THREAD

**Issue by LeanDerVorausdenkende** [LeanDerVorausdenkende/10a-Kreuzwortraetselwettbewerb#6]
"**Notice**: Undefined index: crossword_map in **C:\Users\Leander\Documents\XAMPP\htdocs\GitHub\10a-Kreuzwortraetselwettbewerb\src\Controller\CrosswordController.php** on line **18**"

![grafik](https://user-images.githubusercontent.com/57540049/80342286-31b0d100-8864-11ea-9d91-8acbb1964c61.png)

**Comment by AntonderDenker** [comment]
Will be fixed in next update
